### ISSUE TITLE
I have a  problem for execute sqli-hunter

### ISSUE THREAD

**Issue by Marcio861** [zt2/sqli-hunter#17]
please help me
not running sqli-hunter

send  request and log:

└─$ sudo ruby bin/sqli-hunter.rb

[sudo] password for kernel: 
/var/lib/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find activemodel-6.0.3.2 in any of the sources (Bundler::GemNotFound)
        from /var/lib/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
        from /var/lib/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
        from /var/lib/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
        from /var/lib/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
        from /var/lib/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
        from /var/lib/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
        from /var/lib/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
        from /var/lib/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
        from /home/kernel/Desktop/Hacking/sqli-hunter/lib/hunter/proxy.rb:9:in `<top (required)>'
        from /home/kernel/Desktop/Hacking/sqli-hunter/lib/hunter.rb:15:in `require_relative'
        from /home/kernel/Desktop/Hacking/sqli-hunter/lib/hunter.rb:15:in `<module:Hunter>'
        from /home/kernel/Desktop/Hacking/sqli-hunter/lib/hunter.rb:6:in `<top (required)>'
        from bin/sqli-hunter.rb:13:in `require_relative'
        from bin/sqli-hunter.rb:13:in `<main>'

**Comment by zt2** [comment]
It seems you have a problem with dependencies. Please check gem 'activemodel' is in your Ruby environment.
Run `bundler install`.

**Comment by Marcio861** [comment]
ok, maked, but now is new problem:

![image](https://user-images.githubusercontent.com/68037649/195172216-a2b9c21c-2809-475c-a55e-e4f43cef2b0c.png)

**Comment by zt2** [comment]
It was because `sqli-hunter` could not find any valid certificate. You could solve this problem simply by changing your directory to `bin`
